name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.14.x, 1.15.x, 1.16.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race ./... -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest' && startsWith(matrix.go-version, '1.16')
      uses: codecov/codecov-action@v2.0.2
      with:
        file: ./coverage.out
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
