name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  query:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.19.x, 1.20.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test -race ./... -coverprofile=coverage.out -covermode=atomic
    - uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest' && startsWith(matrix.go-version, '1.20')
      with:
        name: coverage-report-files
        path: ./coverage.out
  query-extractor-yaml:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.19.x, 1.20.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./extractor/yaml
    steps:
    - name: Install Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test -race ./... -coverprofile=coverage.out -covermode=atomic
    - uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest' && startsWith(matrix.go-version, '1.20')
      with:
        name: coverage-report-files
        path: ./extractor/yaml/coverage.out
  collect-metrics:
    name: collect metrics
    needs:
      - query
      - query-extractor-yaml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: coverage-report-files
    - uses: k1LoW/octocov-action@v0
