name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  query:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: go test -race ./... -coverpkg=./... -coverprofile=coverage.out -covermode=atomic
    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.go-version, '1.20')
      with:
        name: query-coverage-report
        path: ./coverage.out

  query-extractor-yaml:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extractor/yaml
    steps:
    - name: Install Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: go test -race ./... -coverpkg=./... -coverprofile=coverage.out -covermode=atomic
    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.go-version, '1.20')
      with:
        name: query-extractor-yaml-coverage-report
        path: ./extractor/yaml/coverage.out

  collect-metrics:
    name: collect metrics
    needs:
      - query
      - query-extractor-yaml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: query-coverage-report
        path: ./coverage.out
    - uses: actions/download-artifact@v3
      with:
        name: query-extractor-yaml-coverage-report
        path: ./extractor/yaml/coverage.out
    - uses: k1LoW/octocov-action@v0
